[package]
name = "apx"
version = "0.1.17"
edition = "2024"
build = "build.rs"

rust-version = "1.88"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
opt-level = "z"
panic = "abort"

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module", "abi3-py39"] }
clap = { version = "4", features = ["derive"] }
dirs = "5.0"
dialoguer = "0.11.0"
indicatif = "0.17.9"
rand = "0.8.5"
tera = "1.20.0"
toml = "0.8.20"
walkdir = "2.5.0"
chrono = "0.4"
axum = { version = "0.8.8", features = ["ws"] }
reqwest = { version = "0.13.1", features = ["blocking", "json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9"
tokio = { version = "1.49", features = ["rt-multi-thread", "macros", "sync", "process", "io-util", "signal", "io-std"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7", features = ["io"] }
futures-util = "0.3.31"
sysinfo = "0.33.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
opentelemetry = "0.29"
opentelemetry_sdk = { version = "0.29", features = ["rt-tokio", "logs"] }
opentelemetry-otlp = { version = "0.29", features = ["http-json", "logs"] }
opentelemetry-appender-tracing = "0.29"
notify = "8.2.0"
tokio-tungstenite = { version = "0.28", features = [
  "connect",
  "handshake",
  "stream",
  "rustls-tls-webpki-roots"
]}
tokio-postgres = { version = "0.7.16", features = ["runtime"] }
schemars = "1.2.0"
biome_css_parser = "0.5.8"
biome_css_syntax = "0.5.8"
biome_rowan = "0.5.8"
url = "2.5.8"
lancedb = { version = "0.23.1", default-features = false }
arrow = "56.2.0"
zip = "2.2"
lance-index = "1.0.1"
toml_edit = "0.24.0"
rayon = "1.11.0"
hex = "0.4"
rusqlite = { version = "0.38.0", features = ["bundled"] }
opentelemetry-proto = "0.31.0"
prost = "0.14.3"

[dev-dependencies]
tempfile = "3.15"
