[package]
name = "apx-common"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
rusqlite.workspace = true
chrono.workspace = true
dirs.workspace = true
tracing.workspace = true
